config/routes.rb
BookLove::Application.routes.draw do
  
  devise_for :users

  resources :authors do
    resources :books
  end

  root :to => "home#index"

  get '/test/:author', to: 'books#author_test'

  #make sure that a params[:author] value is sent in the POST data.
  post '/test/post', to: 'books#author_test'


end

# new_user_session GET    /users/sign_in(.:format)                     devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                     devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                    devise/sessions#destroy
#            user_password POST   /users/password(.:format)                    devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)               devise/passwords#edit
#                          PUT    /users/password(.:format)                    devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                      devise/registrations#cancel
#        user_registration POST   /users(.:format)                             devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                     devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                        devise/registrations#edit
#                          PUT    /users(.:format)                             devise/registrations#update
#                          DELETE /users(.:format)                             devise/registrations#destroy
#             author_books GET    /authors/:author_id/books(.:format)          books#index
#                          POST   /authors/:author_id/books(.:format)          books#create
#          new_author_book GET    /authors/:author_id/books/new(.:format)      books#new
#         edit_author_book GET    /authors/:author_id/books/:id/edit(.:format) books#edit
#              author_book GET    /authors/:author_id/books/:id(.:format)      books#show
#                          PUT    /authors/:author_id/books/:id(.:format)      books#update
#                          DELETE /authors/:author_id/books/:id(.:format)      books#destroy
#                  authors GET    /authors(.:format)                           authors#index
#                          POST   /authors(.:format)                           authors#create
#               new_author GET    /authors/new(.:format)                       authors#new
#              edit_author GET    /authors/:id/edit(.:format)                  authors#edit
#                   author GET    /authors/:id(.:format)                       authors#show
#                          PUT    /authors/:id(.:format)                       authors#update
#                          DELETE /authors/:id(.:format)                       authors#destroy
#                     root        /                                            home#index

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :image_url, :name
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author_id, :title
  belongs_to :author
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController


	include LoveBooks

	def index
		@authors = Author.all
	end

	def show
		@author = Author.find(params[:id])
	end

	def new
		@author = Author.new
	end

	def create
		author = Author.create(params[:author])
		titles = get_titles(params[:author][:name])


		titles.each do |title| 
			author.books << Book.create(title: title)
		end

		redirect_to author_path(author)
	end


	def edit
		@author = Author.find(params[:id])
	end

	def update
		author = Author.find(params[:id])
		author.update_attributes(params[:author])

		redirect_to root_path
	end

	def destroy
		author = Author.find(params[:id])
		author.destroy

		redirect_to root_path
	end



	

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


	include LoveBooks

	def index

	end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<h2>Edit Author</h2>

<%= form_for @author do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :image_url %>
	<%= f.text_field :image_url %>
	<%= f.submit %>
<% end %>

app/views/authors/index.html.erb
<img alt="full screen background image" src="<%= asset_path 'book_piles.jpeg' %>" id="full-screen-background-image" class="desaturate" /> 
<div class="center_me">
	<h2>Getting listy...</h2>

	<ul class='authors'>
		<% @authors.each do |author| %>
			<li class="nav-item"><%= author.name %></li>	
			<i class="icon-eye-open"><%= link_to 'Show', author %></i>
			<i class="icon-trash"><%= link_to 'Delete', author_path(author),  method: :delete %></i>
		</br>
		<br>

		<% end %>
	</ul>
</div>

app/views/authors/new.html.erb
<img alt="full screen background image" src="<%= asset_path 'typewriter.jpg' %>" id="full-screen-background-image" class="desaturate" />

<div class="center_me">
	<h2>Get your author love on.</h2>

	<%= form_for @author, html: { class: "pure-form pure-form-aligned"} do |f| %>
		<fieldset>
		        <div class="pure-control-group">
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>
				<div class="pure-control-group">	
					<%= f.label :image_url %>
					<%= f.text_field :image_url %>
				</div>	
					<%= f.submit class: "pure-button pure-button-primary" %>
	    </fieldset>
	<% end %> 
</div>   

app/views/authors/show.html.erb
<div class="center_big">
	<h2>Show Author</h2>

	<h1>Meet <%= @author.name %></h1>
	<div class="circle">
	<img class="image-wrap" src="<%= @author.image_url %>" />
	</div>

	<ul>
	<% @author.books.each do |book| %>
		<li class="nav-item"><%= book.title %></li>
	<% end %>	
	</ul>
</div>

app/views/books/edit.html.erb
<h2>Edit Book</h2>

<%= form_for @book do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.submit %>
<% end %>

app/views/books/index.html.erb
<h2>Book Indexr</h2>

<ul class='books'>
	<% @books.each do |book| %>
		<li><%= book.title %></li>
	<% end %>
</ul>

app/views/books/new.html.erb
<h2>New Books?</h2>

app/views/home/index.html.erb
<img alt="full screen background image" src="<%= asset_path 'bathtub_great.jpg' %>" id="full-screen-background-image" class="desaturate" /> 
  

<!-- THIS IS THE SIGN IN STATUS -->

  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BookLove</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  
  <div id="wrapper">
  	
    <div id="menu" class="pure-menu pure-menu-open">
         <ul class="nav">
          <li id="heart" class="nav-item"><i class="icon-heart"></i></li>
          <li class="nav-item"><%= link_to 'Home', root_path%></li>
          <li class="nav-item"><%= link_to 'Add Author', new_author_path %></li>
          <li class="nav-item"><%= link_to 'Past Affairs', authors_path %></li>
    		</ul>
    </div>	
    

   <div class="main">

     <%= yield %>

   </div>

</div>
</body>
<html>